security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        gd_user:
            id: App\Services\GDUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_public:
            pattern: ^/api/public
            security: false

        api:
            pattern: ^/api/
            anonymous: true
            logout: ~

            guard:
                entry_point: App\Services\PlainPasswordAuthenticator
                authenticators:
                    - App\Services\PlainPasswordAuthenticator
                    - App\Services\TokenAuthenticator

            stateless: true

        main:
            anonymous: ~
            logout: ~


            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/api/, roles: ROLE_USER }
         - { path: ^/api/mod/, roles: ROLE_MOD }
         - { path: ^/api/eldermod/, roles: ROLE_ELDERMOD }
         - { path: ^/api/admin/, roles: ROLE_ADMIN }
