controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: '/xxx'
    methods: [GET,POST]

api_controller:
    resource: ../../src/ApiController/
    type: annotation
    prefix: '/api'